### PR TITLE
Prefix all names in internal modules with `__`

### LINKED ISSUE #1714: Local operator definitions in internal modules (e.g. `Apalache.tla`) cause namespace collisions
## Description

Internal modules sometimes define local operators, e.g.
```
LET T == S \ {w} IN ...
```
in `Apalache.tla`. This causes collisions when a module defines, for example `CONSTANT T` _and_ `EXTENDS Apalache`

We should hide _all_ operator and variable names used in internal modules that are meant to function as generic libraries to be extended (e.g. by prefixing with `__`).

### PR DESCRIPTION
**Pull request by Kukovec**
- [ ] Tests added for any new code
- [ ] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

All of the changes are purely syntactic.

closes #1714

### CODE REVIEW

**Review by konnov — APPROVED** [review]
Looks great!

**Comment by Kukovec** [comment]
For some reason none of these were flagged when I ran `mdx-test.py` locally, is that script still up-to-date?

**Comment by shonfeder** [comment]
What does “these”? Refer to?

I’d the integrations didn’t fail locally, is it possible that’s because you didn’t rebuild the package first (this is done automatically if you use the make target), or because it’s the dockerized app that’s failing and you didn’t run that?

**Comment by Kukovec** [comment]
I probably just forgot to build.

**Pull request merged**
