### PR TITLE
`types` package refactor

### PR DESCRIPTION
**Pull request by Kukovec**
- [ ] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] [Entries added to `./unreleased/`][changelog format] for any new functionality

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

Partially addresses #1907 and #2229.

Changelist:
- typechecker pass, previously in types/pass moved to (newly created) passes module (preparation for #2229)
- Minor utilities moved to `tlair` (`ModelValueHandler`)
- All typed-builder related classes moved down to `tlair` from `types`
    - Minor change: `ScopedBuilder.parse` has been removed, as it was not a builder utility anyhow, and caused dependency issues. 
- `UJsonToTlaViaBuilder` now has IR-dependencies only, moved to `io/json`. Notably, #2226 is not yet closed.

`tla-types` now essentially contains just the typechecker classes, and no generic TT1 utilities.

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]
Looks like a helpful reorganization to me! Thanks! :D

**Comment by Kukovec** [comment]
> Looks like you broke a reference while moving stuff around: https://github.com/informalsystems/apalache/actions/runs/3275089256/jobs/5389482377#step:4:58

If that were true, I doubt the actual runs would pass. Idk, I'll look into it tomorrow.

**Comment by shonfeder** [comment]
@Kukovec https://github.com/informalsystems/apalache/commit/90cc8f00ada8152e79c5f1394809bfa585fc6704 should fix the documentation reference errors. You can merge in https://github.com/informalsystems/apalache/compare/js/packageRefactor/shon/fixdoclinks if you like how it.

**Review by konnov — APPROVED** [review]
Looks good to me!

**Comment by Kukovec** [comment]
Thanks @shonfeder

**Pull request merged**
