### PR TITLE
Fix 1752 by de-duplicating sets

### PR DESCRIPTION
**Pull request by konnov**
This PR fixes the tricky issue discovered in #1752, which is related to the underlying representation of sets. Basically, the function domain may point to two cells `c_1` and `c_2` that are equal in an SMT model. In this case, the function relation would contain two pairs `(c_1, c_3)` and `(c_2, c_4)`. As a result, the function may sometimes return `c_3` and sometimes return `c_4`, when applied to `c_1 = c_2`.

To fix this bug, we have to de-duplicate the set representation. As we have been already doing something similar in `CardinalityRule` and `FoldSetRule`, I have extracted deduplication into `SetOps.dedup` and refactored the two rules to use it. Having deduplication, it was trivial to fix `CherryPick` to pick functions in a sound way.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

**Review by rodrigo7491 — COMMENTED** [review]
The changes look sound to me, but the fact that the integration tests are taking more than one hour needs to be investigated. Also, I imagine you meant to link #1752 in the PR's description.

**Comment by konnov** [comment]
It's weird that it takes so long.

**Comment by shonfeder** [comment]
The integration test on which things were hanging appears to be

[check TestSets.tla reports no error (array-encoding)](https://github.com/informalsystems/apalache/blob/unstable/test/tla/cli-integration-tests.md#check-testsetstla-reports-no-error-array-encoding)

**Comment by konnov** [comment]
I think `SetOps.dedup` should be fixed for the arrays encoding. It is now used in the implementation of `Cardinality` and `FoldSet`.

**Comment by konnov** [comment]
Independently of a fix, I would really love to understand why it takes z3 more than 6 hours to solve this instance (with the incorrect encoding). This may help us understanding the performance bottlenecks.

**Comment by rodrigo7491** [comment]
@konnov Sure, let's have a look at it.

**Comment by konnov** [comment]
@rodrigo7491 and I have debugged it. The bug was not about the arrays encoding at all. Actually, I have introduced an exponentially large expression by accident, so any recursive code over the expression was stuck forever.

It's amazing that we have caught that via the integration tests! 🎉

**Review by rodrigo7491 — APPROVED** [review]
LGTM

**Pull request merged**
