### PR TITLE
Bump JDK version (+ Scala version in docs)

### LINKED ISSUE #1600: Update Java and Scala dependencies in docs
As described in https://github.com/informalsystems/apalache/pull/1598#discussion_r843729858, we are currently using Scala 2.12.15 in `build.sbt`; the info in `docs/src/apalache/installation/source.md` is outdated. We can probably also bump the Java dependency, preferably to an LTS release, see the [compatiblity table](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#version-compatibility-table).

### PR DESCRIPTION
**Pull request by thpani**
Closes #1600

As discussed in https://github.com/informalsystems/apalache/pull/1598#discussion_r843729858, bump the recommended JDK version. Also, sync docs to our current Scala version.

In particular:
- Scala is already `2.12.15` in `build.sbt` – this PR only syncs the docs.
- Recommended Java is bumped to JDK17, which has LTS support until at least 2025.
  - Our currently recommended JDK8 reached GA in 2014 and already went through [End of Public Updates](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).
  - AdoptOpenJDK moved to the Eclipse Foundation and is now called Eclipse Temurin, this is reflected in the docs.

I've been running Apalache under JDK17 since I joined, and it's working just fine.

- [x] bump version in docs
- [x] bump github workflows
- [x] update release notes

### CODE REVIEW

**Review by konnov — APPROVED** [review]
LGTM

**Review by shonfeder — APPROVED** [review]
Looks great. Thanks!

**Comment by thpani** [comment]
Forgot about `flake.nix` and the `Dockerfile`. @shonfeder PTAL

**Review by shonfeder — APPROVED** [review]
LGTM

Would be nice to consolidate this configuration more so we don't have to change it all over the place. Moving to a more nixified approach may be the way forward for that... I'll think about it and consult with Gabriela.

Thanks for the update!

**Pull request merged**
