### PR TITLE
Add formatting automation

### PR DESCRIPTION
**Pull request by shonfeder**
- Adds formatting checks to our build configuration.
- Reformats all source files.
- Adds the formatting checks into our CI

Best to review by individual commits. The one massive formatting commit in 9608b88  only needs to be reviewed to decide if we are OK with his formatting, or if we'd like to tweak the configs. scalafmt is very configurable, See https://scalameta.org/scalafmt/docs/configuration.html (I've just added one config which they say is "popular").

### CODE REVIEW

**Comment by shonfeder** [comment]
Tested to ensure the CI fails on incorrect formatting.

https://github.com/informalsystems/apalache/pull/496/checks?check_run_id=1765999521

It also prints instructions on how to fix it.

**Review by konnov — COMMENTED** [review]
Do we really need maxColumn=80? E.g., idea has maxColumn=120 by default. The reformatted code is significantly longer in many case.

**Comment by shonfeder** [comment]
> Do we really need maxColumn=80? E.g., idea has maxColumn=120 by default. The reformatted code is significantly longer in many case.

I don't have any preferences re: our formatting. I'll change the maxColumn to 120. Anything else you'd like to see tweaked about the configuration?

**Comment by konnov** [comment]
Could you re-run it with 120 chars? Maybe all of my problems come from that

**Comment by konnov** [comment]
I am trying `preset=Scala.js`. This is probably the standard convention: https://docs.scala-lang.org/style/

**Comment by konnov** [comment]
These settings look good to me:

```
maxColumn = 120
preset = Scala.js
```

**Comment by shonfeder** [comment]
Configured as specified.

**Review by konnov — APPROVED** [review]
The settings look good to me and they actually make more sense than what I used before

**Pull request merged**
