### PR TITLE
Update TLC cfg file syntax

### PR DESCRIPTION
**Pull request by heidihoward**
Action constraints in cfg files are labelled with `ACTION_CONSTRAINT` or `ACTION_CONSTRAINTS`, not `ACTION-CONSTRAINT` or `ACTION-CONSTRAINTS` (underscore instead of a hyphen).

Based on this comment in the TLC source code, I believe it changed from a hyphen to an underscore in 2009 https://github.com/tlaplus/tlaplus/blob/a41cbafc66b1dd225156aaca38ad35ec330f4ae9/toolbox/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/launch/TLCModelLaunchDelegate.java#L588

### CODE REVIEW

**Comment by lemmy** [comment]
TLCModelLaunchDelegate is Toolbox code.  I don't think that TLC ever accepted the hyphenated variants; at least not within the last 15 years:  https://github.com/tlaplus/tlaplus/blob/a401ad39044e5014cb07a9588611041c1d55596d/tlatools/src/tlc2/tool/ModelConfig.java#L43-L44

**Comment by heidihoward** [comment]
Thanks @lemmy for clarifying. Perhaps, this is based on the grammar from the specifying systems books which uses the hyphenated version

**Comment by shonfeder** [comment]
Thanks for the update @heidihoward ! :pray:

**Review by konnov — APPROVED** [review]
Thanks @heidihoward for taking care of it! It may be that I've copied this definition from the book.

**Pull request merged**
