### PR TITLE
Move internal operators to ApalacheInternalOper

### LINKED ISSUE #1287: [FEATURE] Move some operators to ApalacheInternalOper
A number of new IR operators have been added to `ApalacheOper` when working towards #360. These new operators are not exposed to users and, as suggested by @konnov, could be moved to a new `SMTOper` class.

### PR DESCRIPTION
**Pull request by rodrigo7491**
- [ ] ~Tests added for any new code~
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [ ] ~Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~

The core of this PR is the move of six IR operators from `ApalacheOper` to `ApalacheInternalOper`. This affected many files. Most of them were handled by simple substitution, but I took the opportunity to rework some of the cases in which the touched operators were used, aiming to make the code clearer. Closes #1287.

### CODE REVIEW

**Comment by rodrigo7491** [comment]
The CI is giving the following error when running the unit test for macos:
```
Run codecov/codecov-action@v2
  with:
    token: ***
  env:
    APALACHE_FATAL_WARNINGS: true
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.322-6/x64/Contents/Home
    APALACHE_HOME: /Users/runner/work/apalache/apalache
==> macos OS detected
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
```
I only have Linux and cannot reproduce this. Thoughts @konnov?

**Comment by konnov** [comment]
It looks like the service is not available. Perhaps re-run the build?

**Comment by rodrigo7491** [comment]
That worked! Since only the check for macos failed, I immediately assumed it was an OS issue.

**Review by konnov — APPROVED** [review]
Looks good!

**Pull request merged**
