### PR TITLE
Simplification of function sets with statically empty codomains

### LINKED ISSUE #1058: [BUG] Unandled RunTime exception: "The set ... is statically empty. Pick should not be called on that."
## Description

Selecting functions out of sets of functions with empty domains xor codomains causes an uncaught runtime exception.

## Input specification

```tla
------------------- MODULE BugTODO -----------------------
EXTENDS Naturals

VARIABLE
  \* @type: Int -> Int;
  f

Init == f \in [{1} -> {}]

Next == f' = f
------------------------------------------------------------
============================================================
```

Produces

```
Unhandled exception                                               E@18:06:20.784
java.lang.RuntimeException: The set $C$7 is statically empty. Pick should not be called on that.
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pick(CherryPick.scala:75)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$pickFunFromFunSet$2(CherryPick.scala:638)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$pickFunFromFunSet$2$adapted(CherryPick.scala:637)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickFunFromFunSet(CherryPick.scala:637)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pick(CherryPick.scala:46)
	at at.forsyte.apalache.tla.bmcmt.rules.QuantRule.skolemExistsByPick(QuantRule.scala:254)
	at at.forsyte.apalache.tla.bmcmt.rules.QuantRule.apply(QuantRule.scala:56)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:100)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:34)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.prepareTransition(ConstrainedTransitionExecutor.scala:93)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6(SeqModelChecker.scala:151)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6$adapted(SeqModelChecker.scala:145)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:145)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:67)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:131)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:98)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:262)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:166)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:402)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:166)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## The command line parameters used to run the tool

```
check --init=Init --next=Next
```

## Additional context

Discovered while investigating a user report of possibly bogus `is not assigned a value` error.

Note that when *both* domain and codomain are empty, no crash occurs.

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] [Entries added to `./unreleased/`][changelog format] for any new functionality

closes #1058 

Recall that `[A -> B]` is defined as the set of functions `f`, for which `D(f) = A` and `\A x \in A: f(x) \in B`. If `B = {}`, then `f(x) \in B` can never be true, so `\A x \in A: f(x) \in B` is `\A x \in A: FALSE`, which depends on whether `A` is exactly empty or not.

The PR introduces a preprocessing step, which rewrites `[A -> {}]` into 
  1. `{}`, if `A` is not statically empty
  1. `[{} -> Gen(1)]` if `A = {}`. The reason is that the only member of `[{} -> B]` for _any_ `B` is the empty function. In terms of Apalache, this means a function, which evaluates to an arbitrary (type-correct) value everywhere, so we can freely replace `B` with a set of of arbitrary type-correct values (produced via `Gen`).

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

### CODE REVIEW

**Review by thpani — APPROVED** [review]
👍

**Comment by konnov** [comment]
This is indeed a tricky case. Your analysis seems right to me. Do you know the behavior of TLC in this case? It would be good to be consistent there.

**Comment by Kukovec** [comment]
> This is indeed a tricky case. Your analysis seems right to me. Do you know the behavior of TLC in this case? It would be good to be consistent there.

So I tested it with
```tla
Init == 
    /\ step = 0
    /\ FnInit
Next == 
    /\ f' = f
    /\ step = 1
Inv == 
    step = 0
```
TLC finds 0 starting states when `FnInit == f = \in [{1} -> {}]`, and (as expected), finds a violation with `f = <<>>` in both cases where `FnInit == f \in [{} -> {}]` and `f \in [{} -> {1}]`.

**Comment by Kukovec** [comment]
> Thanks! Indeed, `[ x \in {} |-> {} ]` can be treated as `<<>>`. I have not though about it.

Well, not in Apalache, since `<<>>` is not a function of any kind.

**Pull request merged**
