### PR TITLE
Check invariants at step 0 with `--discard-disabled=false` and `InvariantMode.BeforeJoin`

### LINKED ISSUE #2158: discard-disable=false seems buggy
Hello, 
I'm using the latest docker image and getting strange results with `--discard-disabled=false`.
Consider the following spec:
```
-------------------------------- MODULE Test --------------------------------
Init == TRUE
Next == TRUE
Inv == FALSE
=============================================================================
```
The command `$APALACHE_HOME/script/run-docker.sh check --inv=Inv --discard-disabled=false Test.tla` reports no errors.
Am I misunderstanding something or is this a bug?

### PR DESCRIPTION
**Pull request by thpani**
Check invariants at step 0 when `--discard-disabled=false` and `InvariantMode.BeforeJoin`.

Fixes #2158.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] [Entries added to `./unreleased/`][changelog format] for any new functionality

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

### CODE REVIEW

**Comment by thpani** [comment]
Thanks to @konnov for helping debug this!

**Review by shonfeder — CHANGES_REQUESTED** [review]
The change looks good!

This should include a regression test to ensure this behavior doesn't break again however. I can add that in, since Thomas is in flight :)

**Comment by shonfeder** [comment]
Good find and fix! :D

**Review by shonfeder — APPROVED** [review]

**Comment by thpani** [comment]
Thanks @shonfeder! 🙏 
Yeah... I feel like we need more systematic testing around the exploration part in general, though I'm not sure how...

**Pull request merged**
