### PR TITLE
Implement `--output` for `typecheck`

### LINKED ISSUE #1284: [FEATURE] Add the flag `--output` to typecheck
Related to #1281, there is no simple way to produce json after the `typecheck` pass. It's possible to use `--write-intermediate=1` and check the produced intermediate file. However, this is too hard to use.

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

Also fixes decoding of recursive functions (untracked bug).

Closes #1284

### CODE REVIEW

**Review by gabrielamafra — APPROVED** [review]
LGTM

**Comment by konnov** [comment]
Maybe we should reuse the spec from `tla-types/src/test/resources/MegaSpec1.tla`. It contains pretty much all variations of operators.

**Review by shonfeder — APPROVED** [review]

**Comment by shonfeder** [comment]
@konnov iiuc, this PR is only introducing the output file flag. So I wouldn't think it's the right place to check a megaspec. Seems that would be better fit for a PR that was concerned with the parser or serializer itself, rather than just the plumbing of printing to a file.

**Comment by Kukovec** [comment]
> @konnov iiuc, this PR is only introducing the output file flag. So I wouldn't think it's the right place to check a megaspec. Seems that would be better fit for a PR that was concerned with the parser or serializer itself, rather than just the plumbing of printing to a file.

I understood this as Igor wanting to run the integration test on `MegaSpec1`, as opposed to `Annotations`. Is that right @konnov?

**Comment by konnov** [comment]
yes, that's right. We can also do it in a unit test

**Comment by shonfeder** [comment]
Yeah, I'm suggesting that we probably don't want to run the integration test on the megaspec, esp not if we're just testing that output files are generated.

If we are testing that the JSON or TLA constructed is correct, then we'd want the megaspec I guess? But I wonder if that's not a better suited for unit tests or even PBT?

**Comment by shonfeder** [comment]
My point being, iiuc, this PR is only introducing dumping some stuff to a file. It is not introducing the logic of how to parse a spec, type check it, then reconstruct TLA or JSON from the AST. But the mega spec seems targeted at the latter.

**Pull request merged**
