### PR TITLE
Adapt assignment solving for non-nullary and recursive operators

### PR DESCRIPTION
**Pull request by Kukovec**
- ~[ ] Tests added for any new code~
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- ~[ ] Documentation added for any new functionality~
- ~[ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality~

This PR, on its own, does not add or remove visible functionality. It addresses point (1) of #846. Due to the order of passes, the generalizations cover scenarios which are currently impossible, but will be relevant in phase (2) of #846.

### CODE REVIEW

**Comment by konnov** [comment]
Nice! It would be good to have some integration tests though.

**Comment by Kukovec** [comment]
> Nice! It would be good to have some integration tests though.

That would be pointless until phase (2), because inlining and unrolling erase all the test cases where this change would differ from the current implementation.

**Comment by konnov** [comment]
Makes sense. Then unit tests?

**Review by konnov — APPROVED** [review]
Looks good. Does it mean that we could replace `x' = e` with `x' := e` after this pass? I would prefer doing that right after running the type checker.

**Comment by Kukovec** [comment]
> Looks good. Does it mean that we could replace `x' = e` with `x' := e` after this pass? I would prefer doing that right after running the type checker.

`TransitionPassImpl`, already does `:=` introduction, though I suppose you could rework the passes so that this independently happens earlier.

**Comment by konnov** [comment]
> `TransitionPassImpl`, already does `:=` introduction, though I suppose you could rework the passes so that this independently happens earlier.

Sure. But `TransitionPassImpl` is run very late in the pipeline.

**Pull request merged**
