### PR TITLE
WIP Improved cover analysis output

### LINKED ISSUE #298: [FEATURE] Friendly assignment analysis
The new `CoverAnalysisPass` produces extremely useful output about the state variables assigned in every operator. However, it is mostly unreadable on large examples:

```
TRUSTING_PERIOD covers: 
...
SwitchToPrimary covers: Faulty, blockchain, commonHeight, evidences, fetchedLightBlocks1, fetchedLightBlocks1b, fetchedLightBlocks2, lightBlockStatus1, lightBlockStatus1b, lightBlockStatus2, nextHeightToTry, now, state
Next covers: Faulty, blockchain, commonHeight, evidences, fetchedLightBlocks1, fetchedLightBlocks1b, fetchedLightBlocks2, lightBlockStatus1, lightBlockStatus1b, lightBlockStatus2, nextHeightToTry, now, state
TARGET_HEIGHT covers: 
...
```

(Note that `TRUSTING_PERIOD` and `TARGET_HEIGHT` are constants in this example, so the users are not interested in that output.)

Moreover, the users would not know what `cover` means and expect branch coverage, statement coverage, or similar.

A more informative output for the possible assignments may look like follows:

```
Foo.tla:200:8-200:75: SwitchToPrimary may update nextHeightToTry' 
Foo.tla:201:8-201:47: SwitchToPrimary may update state' 
Foo.tla:202:8-202:50: SwitchToPrimary may update blockchain' 
```

If you pad this info into three columns, that will be extremely useful to see, even if there are no bugs in the assignments.

### PR DESCRIPTION
**Pull request by Kukovec**
For example, given
```
--------------------------- MODULE test -------------------------------------

EXTENDS Integers

VARIABLE x,y

Init == x = 1 /\ y = 1

A1 == x' = 1 \/ x' = 2
A2 == x' = 3 \/ x' = 4
B1 == y' = 1 \/ y = 2
B2 == x' = 1 /\ (y' = 3 \/ y' = 4)

Next == 
    \/ A1 /\ B1
    \/ A1 /\ B2
    \/ A2 /\ B1
    \/ A2 /\ B2

=============================================================================
```

the new output is
```
test.tla:7:9-7:13   : Init may update x
test.tla:7:18-7:22  : Init may update y
test.tla:9:7-9:12   :   A1 may update x
test.tla:9:17-9:22  :   A1 may update x
test.tla:10:7-10:12 :   A2 may update x
test.tla:10:17-10:22:   A2 may update x
test.tla:11:7-11:12 :   B1 may update y
test.tla:12:18-12:23:   B2 may update y
test.tla:12:28-12:33:   B2 may update y

test.tla:7:9-7:22   : Init always updates: x, y
test.tla:9:7-9:22   :   A1 always updates: x
test.tla:10:7-10:22 :   A2 always updates: x
test.tla:11:7-11:21 :   B1 sometimes does not update: y 	 [WARNING!] 
test.tla:12:7-12:34 :   B2 always updates: y
```

Closes #298.

### CODE REVIEW

**Comment by Kukovec** [comment]
Side-note, I see some tests are failing because source information for operators is unavailable, this is an indication of an unrelated underlying bug.

**Comment by shonfeder** [comment]
> Side-note, I see some tests are failing because source information for operators is unavailable, this is an indication of an unrelated underlying bug.

I suggest we fix the underling but here, or else in a separate PR that we merge in ahead of this one. We don't want to break the integration tests on the development branch, because it could then hide other regressions that show up later.

**Comment by Kukovec** [comment]
The reordering of passes to accommodate the new cover analysis (specifically, addressing the incompatibility with inlining, which now deletes operator definitions from the module) should get its own PR, so this one should be put on hold until all bugs arising from the reordering are isolated, as not to get saturated with commits not related to cover analysis.

**Comment by shonfeder** [comment]
(Marked as WIP so it doesn't show in our daily alerts for stale PRs) :)

**Comment by konnov** [comment]
What is the status of this PR?

**Comment by Kukovec** [comment]
> 
> 
> What is the status of this PR?

Since other PRs (#343, previously #347) are linked to bugs and are thus more pressing, work on this will resume after #343 closes.

**Comment by Kukovec** [comment]
#366 removed the need for cover analysis, so I'm scrapping this PR.

**Pull request closed without merging**
