### PR TITLE
Release 0.7.2

### PR DESCRIPTION
**Pull request by shonfeder**
## 0.7.2 [RELEASE]

 * fixed an omitted version number update

--- 

**Note** that this cherry picks in just the bug fixes and changelog updates from unstable, and does not merge all of unstable into master.

### CODE REVIEW

**Comment by shonfeder** [comment]
Looks like `mvn versions:set -DremoveSnapshot` should that just be in this branch, or in unstable and then cherry picked in? How have you been doing it to this point?

**Comment by konnov** [comment]
Our releases were so rare that I don't remember :-)

**Comment by shonfeder** [comment]
Ah! OK! We'll just approach it as designing out a new process then. Let me do a little bit of research on standard release cycle for java/scala projects, and I'll loop back here.

**Comment by shonfeder** [comment]
Ok, using the approach with our current set up, I think the `-RELEASE` suffix had to be added in `unstable` or else we'll need to merge the release branch back into `unstable`, which it would be better to avoid. So I've done that.

**Pull request merged**
