### PR TITLE
Added Antipatterns.tla

### LINKED ISSUE #2497: Create a spec containing anitpatterns, for performance testing
Title.

### PR DESCRIPTION
**Pull request by Kukovec**
- [ ] Tests added for any new code
- [ ] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] [Entries added to `./unreleased/`][changelog format] for any new functionality

closes #2497 

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

### CODE REVIEW

**Comment by thpani** [comment]
We should make sure that if someone finds this spec in a couple of years from now, they understand why it is relevant and what it is meant to be used for.

Can you please add some context on what motivates this, ideally to both the spec and either to this PR description or the issue closed by it?

**Comment by Kukovec** [comment]
From the file:
```
The purpose of this file is to collect known antipatterns, so we can measure just how 
much they affect performance, across various versions of Apalache.
As a side-effect of the work done on ADR20, the performance hit when using anipatterns,
while still present, is expected to be less drastic than before.
```

**Review by shonfeder — APPROVED** [review]
LGTM!

**Review by konnov — APPROVED** [review]
Looks good for me too. I may suggest one more pattern: build a list from a function by folding. Happened to me a few times.

**Comment by Kukovec** [comment]
> Looks good for me too. I may suggest one more pattern: build a list from a function by folding. Happened to me a few times.

You mean a seq of the form `<<f[1], f[2], ..., f[n]>>`?

**Comment by konnov** [comment]
> > Looks good for me too. I may suggest one more pattern: build a list from a function by folding. Happened to me a few times.
> 
> You mean a seq of the form `<<f[1], f[2], ..., f[n]>>`?

Yes

**Pull request merged**
