### PR TITLE
isolate calls to stats collection

### PR DESCRIPTION
**Pull request by konnov**
This PR isolates the settings for TLC/Toolbox/Apalache statistics collection, so the tests do not call home.

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]
Nice solution!

**Comment by konnov** [comment]
The docker tests are failing. How shall we deal with the docker setup?

**Comment by shonfeder** [comment]
Ah! I think we can safely bind mount the user's `~/.tlaplus` from their host system into the container. I'll give that a shot here.

**Comment by shonfeder** [comment]
lol, looks like i also found a workaround to approve PR's that you've contributed to :laugh

**Pull request merged**
