### PR TITLE
Add counterexample writer and --temporal flag

### PR DESCRIPTION
**Pull request by shonfeder**
This PR is meant to clean up the git troubles encountered in #1830 and #1873. If we move forward with this PR, it should replace those two.

The "fix" attempted here was to squash merge all changes from branch `1815-with-unstable-merged-in` into a new branch off of unstable.

To try to confirm that his branch includes all the changes, I created a new branch off `unstable` and merged in `1815-with-unstable-merged-in` then did a git diff:

```diff
$  git diff 1815-with-unstable-merged-in..1815-try-to-fix-git
diff --git a/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala b/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
index 570db1cef..4bb18e190 100644
--- a/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
+++ b/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/AbstractCheckerCmd.scala
@@ -40,6 +40,8 @@ abstract class AbstractCheckerCmd(val name: String, description: String)
       executor.passOptions.set("checker.next", next)
     if (inv != "")
       executor.passOptions.set("checker.inv", List(inv))
+    if (temporal != "")
+      executor.passOptions.set("checker.temporal", List(temporal))
     if (cinit != "")
       executor.passOptions.set("checker.cinit", cinit)
     executor.passOptions.set("checker.length", length)
``` 

You can verify this yourself by pulling down the `1815-with-unstable-merged-in` branch and running this yourself.

The two line difference is due to changes needed to adapt to #1858.

Let me know what you think about using this PR to add your changes, @p-offtermatt! Should probably involve a careful check to ensure it includes everything you would expect.

### CODE REVIEW

**Comment by p-offtermatt** [comment]
I looked through the changed files, as well as did the diff you suggested, and as far as I can tell, everything looks proper and as it should be.
I think using this PR to add the changes in should be the way to go.

Thanks for the effort!

**Comment by shonfeder** [comment]
Sounds good! I’ll leave it to you to rename the PR and or tag anyone for reviews that may be needed.

I think at least part of the code has already been reviewed?

**Comment by p-offtermatt** [comment]
All code has already been reviewed as part of https://github.com/informalsystems/apalache/pull/1830 and https://github.com/informalsystems/apalache/pull/1823

**Comment by shonfeder** [comment]
Nice! Why don’t you approve this PR then (I can’t cause I authored it) and we’ll merge it in! :)

**Review by p-offtermatt — APPROVED** [review]

**Comment by thpani** [comment]
Thanks @shonfeder for going the extra mile and cleaning up these branches!

**Pull request merged**
