### PR TITLE
Avoid sets of function sets in Nitpicker

### LINKED ISSUE #1759: Avoid sets of function sets in `CrossTestEncodings`
Follow-up to #1748:
To unblock discovery of new bugs, Nitpicker should temporarily avoid sets of function sets.

### PR DESCRIPTION
**Pull request by thpani**
Temporarily avoid sets of function sets in Nitpicker (aka `CrossTestEncodings`), to unblock discovery of new bugs.

Closes #1759

### CODE REVIEW

**Comment by thpani** [comment]
@rodrigo7491 This patch should help to work around https://github.com/informalsystems/apalache/issues/1748

**Comment by rodrigo7491** [comment]
@thpani Indeed, looking forward to it!

**Comment by rodrigo7491** [comment]
@thpani It seems we are still hitting the same bug, see #1774.

**Review by konnov — APPROVED** [review]
Looks good!

**Pull request merged**
