### PR TITLE
Correct flags on apalache-jar make target

### PR DESCRIPTION
**Pull request by shonfeder**
This is meant to be a speedy build of the jar without running tests,
but I had the flags wrong I think.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [x] Documentation added for any new functionality
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

**Review by konnov — APPROVED** [review]
Looks good. Shall we add a line on that target in the manual? Otherwise, the users will never find it by themselves.

**Comment by shonfeder** [comment]
Turns out the flags like this don't make any difference in running time, and the tests are skipped either way. So I was wrong about the need for this PR. Still, this flag arrangement seems as good as the other.

Where in the manual do you think this should go? (It's currently used in CI).

**Comment by konnov** [comment]
Here looks like a good place: https://apalache.informal.systems/docs/apalache/installation/source.html

**Comment by shonfeder** [comment]
Do you want me to replace the currently advised `make` target that runs the tests with the `make apalache-jar` target?

**Comment by konnov** [comment]
I would say that we should have `make` by default. But you can make a note that if the user wants to bypass the tests and make the build faster (e.g., they do it on regular basis), they can use the special target.

**Comment by shonfeder** [comment]
I don't think we should complicate the installation instructions with superfluous details. I think there should just be one way to install in the user documentation.

Perhaps this additional should note should go in the contributing docs? But then, any contributor who's gonna build should just look at the makefile.

**Comment by shonfeder** [comment]
Tho I guess we already have some optional items in the install instructions. OK I'll add this there.

**Pull request merged**
