### PR TITLE
Encode infinite sets in the arrays encoding

### PR DESCRIPTION
**Pull request by rodrigo7491**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

This PR encodes infinite sets as constant SMT arrays in the arrays encoding. This fixes a problem first mentioned by @konnov when checking a version of [EWD998](https://github.com/tlaplus/Examples/tree/master/specifications/ewd998). It is also the cause of the exception thrown by the arrays encoding mentioned in #1798.

### CODE REVIEW

**Review by konnov — APPROVED** [review]
Nice! There is definitely something about supporting functions of infinite domains in the arrays encoding. However, we should be real careful about not letting cells like that to propagate into the rules that expect bounded sets, e.g., what happens if we do `DOMAN f \union { 1 }`?

**Review by shonfeder — APPROVED** [review]
LGTM

**Comment by thpani** [comment]
Is this ready to be merged?

**Comment by rodrigo7491** [comment]
This PR fixes the immediate crash problem reported on #1798. Further improvements to the handling of infinite sets will be done at a later stage.

**Pull request merged**
