### PR TITLE
Document review locking and code curation

### PR DESCRIPTION
**Pull request by shonfeder**
As per our discussion in today's meeting, this PR documents our convention for
locking PRs until we a chance to review them (when desired) and for our use of
the CODEOWNERS file.

It also includes an unrelated update to the documentation of our branching model.

- [x] Documentation added for any new functionality

### CODE REVIEW

**Review by konnov — APPROVED** [review]
Looks good!

**Review by gabrielamafra — APPROVED** [review]
I like this. I'm still skeptical about how much successful we will be at keeping CODEOWNERS updated so it is useful, but I don't think it will be a burden otherwise, so I'm on board with giving it a shot. I really like the locking review protocol :smile:

**Comment by shonfeder** [comment]
> IIUC, the main problem we had in the past was that PRs where merged faster than people got to look at them.

iiuc, the situation discussed in the meeting was where someone was in the middle of doing a review when a PR got merged.

PR authors can and should still do the things you describe. If they think reviews for some particular contributors are critical, they shouldn’t merge their prs until they get the needed reviews.

Sanctioning the proposed mechanism is just a way of allowing reviewers to quickly communicate and enforce their conviction in the other direction, for cases when they feel their own review is critical. It doesn’t replace the tasks for PR authors.

If there is persistent and problematic disagreement on (b) I agree we should communicate to clarify.

I think Jure has already made use of this mechanism to lock a or pending review l, so it seems it can work in practice.

**Comment by thpani** [comment]
> iiuc, the situation discussed in the meeting was where someone was in the middle of doing a review when a PR got merged.

To prevent this I would need to invoke the locking protocol every time I start a review?

**Pull request merged**
